version: '3.7'
services:
    postgres:
        environment:
            POSTGRES_DB: your_project
            POSTGRES_USER: your_username
            POSTGRES_PASSWORD: your_password
        restart: always
        container_name: projectname_postgres
        build:
         context: .
         dockerfile: dockerfiles/docker_postgres.conf
        volumes:
            - ./dbdata:/var/lib/postgresql/data
    django:
        restart: always
        container_name: projectname_django
        volumes:
         - ./code:/code
         - sock:/sock
        build:
         context: .
         dockerfile: dockerfiles/docker_django.conf
        depends_on:
         - postgres
        command: bash -c "uwsgi --ini /etc/uwsgi.ini &&
                          python /code/hello_example_project/manage.py collectstatic --noinput &&
                          python /code/hello_example_project/manage.py migrate"
        #command: bash -c "chmod 777 -R /var/run/uwsgi/ && uwsgi --ini /etc/uwsgi.ini"
        #command: bash -c "python /code/projectname/manage.py collectstatic --noinput && python /code/projectname/manage.py migrate && python /code/projectname/manage.py runserver 0.0.0.0:8000"
        ports:
         - "8001:8001"
    nginx:
        restart: always
        container_name: projectname_nginx
        volumes:
         - ./code:/code
         - sock:/sock
        build:
         context: .
         dockerfile: dockerfiles/docker_nginx.conf
        depends_on:
         - django
        ports:
          - "8080:8080"
volumes:
 sock: